author: DerFlash
database: true
description: Cube-Nation Warn Plugin
main: de.derflash.plugins.cnwarn.CNWarn
name: CNWarn
startup: postworld
url: http://www.cube-nation.de/
version: '${project.version}'

softdepend:
  - PermissionsEx

commands:
    warn:
        description: warn a player
        usage: /warn help for more information
    watch:
        description: watch a player
        usage: /watch help for more information

permissions:
  cnwarn.watch:
    description: ...
  cubewarn.watch
    description: ...
  cubewarn.staff:
    description: ...
  cubewarn.admin:
    description: ...
