author: DerFlash
database: true
description: Cube-Nation Warn Plugin
main: de.cubenation.plugins.cnwarn.CnWarn
name: CNWarn
startup: postworld
url: http://www.cube-nation.de/
version: '${project.version}'

depend:
  - PluginUtils

permissions:
  cnwarn.watch:
    description: ...
  cubewarn.watch:
    description: ...
  cubewarn.staff:
    description: ...
  cubewarn.admin:
    description: ...
